"""
app.py
------
Home page of the Retail Sales Intelligence dashboard.

This is a pure presentation layer: it only reads artifacts produced by
`Retail_Sales_Forecasting.ipynb` (models/, processed/, predictions/).
No model training happens anywhere in this app.

Run with:
    streamlit run app.py
"""

import streamlit as st

from utils.data_loader import (
    artifacts_missing,
    load_artifact_manifest,
    load_best_model_info,
    load_monthly_sales,
    load_transactions,
)
from utils.styling import apply_page_config, kpi_card, missing_artifact_banner, render_sidebar_branding

apply_page_config("Home", icon="🏠")
render_sidebar_branding()

st.sidebar.info(
    "Use the pages in the sidebar to explore the **Sales Dashboard**, "
    "**Forecast Explorer**, **Anomaly Detection**, and **Demand Segmentation**."
)

st.title("🛒 Retail Sales Intelligence Dashboard")
st.caption(
    "A read-only dashboard over artifacts generated by the companion Jupyter notebook — "
    "no model training happens in this app."
)

missing_artifact_banner(artifacts_missing())

df = load_transactions()
monthly_df = load_monthly_sales()
best_model_info = load_best_model_info()
manifest = load_artifact_manifest()

st.divider()
st.subheader("At a Glance")

if df.empty:
    st.info("No processed data found yet. Run every cell of `Retail_Sales_Forecasting.ipynb` first.")
else:
    total_revenue = df["Sales"].sum()
    total_orders = df["Order ID"].nunique() if "Order ID" in df.columns else len(df)
    avg_order_value = df["Sales"].mean()
    n_categories = df["Category"].nunique() if "Category" in df.columns else 0

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        kpi_card("Total Revenue", f"${total_revenue:,.0f}")
    with col2:
        kpi_card("Total Orders", f"{total_orders:,}")
    with col3:
        kpi_card("Average Order Value", f"${avg_order_value:,.2f}")
    with col4:
        kpi_card("Product Categories", f"{n_categories}")

    if not monthly_df.empty:
        st.line_chart(monthly_df.set_index("Order Date")["Sales"], height=280)

st.divider()

col_a, col_b = st.columns(2)
with col_a:
    st.subheader("🏆 Selected Forecasting Model")
    if best_model_info:
        st.success(f"**{best_model_info.get('best_model', 'N/A')}** — chosen automatically by lowest MAPE")
        st.json(best_model_info.get("metrics", {}))
    else:
        st.info("Run the notebook to generate `reports/best_model.json`.")

with col_b:
    st.subheader("📦 Available Artifacts")
    if manifest:
        st.write(f"Generated: `{manifest.get('generated_at', 'unknown')}`")
        st.write("**Models:**", ", ".join(manifest.get("model_files", [])) or "none")
        st.write("**Processed data:**", ", ".join(manifest.get("processed_files", [])) or "none")
        st.write("**Predictions:**", ", ".join(manifest.get("prediction_files", [])) or "none")
    else:
        st.info("Run the notebook to generate `reports/artifact_manifest.json`.")

st.divider()
st.caption(
    "Navigate using the sidebar: **1 · Sales Dashboard**, **2 · Forecast Explorer**, "
    "**3 · Anomaly Detection**, **4 · Demand Segmentation**."
)
